Accrued Points,Accrue Points Based On,Product,Product Category,Minimum Price,Maximum Price,Minimum Quantity,Maximum Quantity,Loyalty Tier,Loyalty Tier Group,Loyalty Program
80,Product Quantity,Light switches,Electric appliances,100,200,10,20,Gold,Test Tier Group 1,Program Name Test 1
100,Invoice Price,Light switches,Electric appliances,500,2500,50,100,Platinum,Test Tier Group 1,Program Name Test 1