Program,Membership Number,JournalType,JournalSubType,Industry,Partner Name,ActivityDate,JournalDate,ExternalTransactionNumber,Status,ProductCategory,Product,Quantity,TransactionAmount,InvoiceDate,EndDate,ActivityCategory__c,ActivityName__c
Program Name Test 1,24345671,Test Data Accrual,Training,,,,,1,Pending,,,,,,,Sales Training,Annual Sales Training
Program Name Test 1,24345671,Test Data Accrual,Quiz,,,,,2000,Pending,,,,,,,Quiz of the day,Daily Quiz
Program Name Test 1,24345671,Test Data Accrual,Quiz,,,,,2000,Pending,,,,,,,Quiz of the week,Weekly Quiz
Program Name Test 1,24345671,Test Data Accrual,Training,,Stellar PLC,,,2000,Pending,,,,,,,Business Review,Business Review
Program Name Test 1,24345671,Test Data Accrual,Invoice,,Stellar PLC,,,,Pending,Electric appliances,Light switches,3,2500,,,Sales Training,Annual Sales Training
Program Name Test 1,24345671,Test Data Accrual,Order,,Stellar PLC,,,,Pending,Electric appliances,Light switches,3,2500,,,Sales Training,Annual Sales Training